### ISSUE TITLE
Issue with ArrayObject and private $parameters within Endpoint

### ISSUE THREAD

**Issue by ronaldjesse** [unsplash/unsplash-php#101]
Hello,

I'm creating an API layer using unsplash-php package and our CMS frontend / backend and found it impossible to return a json string.

I've got some issues trying to json_encode the ArrayObject object. I've tried using ArrayObject::getArrayCopy(); but it still returns Crew\Unsplash\Photo which is impossible to json_encode as the $parameters attribute is private.

Of course I could format the objects myself, but then I might run into issues later on trying to retrieve attributes that no longer exist, or new attributes.

I'd like to see some sort of toArray() method within ArrayObject which returns an array of Crew\Unsplash\EndPoint::$parameters values.

Would you like me to draft a PR?

Thanks in advance.

**Comment by lukechesser** [comment]
@ronaldjesse hmm yeah that makes sense. Thanks for bringing this up. We'd definitely accept a PR — my PHP skills are pretty lacking these days 😬
