### ISSUE TITLE
Search results different from the website

### ISSUE THREAD

**Issue by th4deu** [unsplash/unsplash-php#103]
Hello,

We're having some issues with the search result for specific keywords. When queried for "digital marketing", for example, the returned images are completely different from the website result or the keywords context. 
I've tried to replace its space for "-", "+", "_", but the result set was the same.

Is there any parameter that I can send to get the result set like if I was searching in the website?

Thanks

**Comment by aaronklaassen** [comment]
@th4deu That's strange; they should match. It's feasible that there would be small (and temporary) differences due to caching on the API side, but they shouldn't be *completely* different. Do you mind giving a list of the first, say 5 or 10 photo IDs that you're getting and a code sample so I can reproduce?

**Comment by th4deu** [comment]
Sup @aaronklaassen, here's a list of the first 10 returned Ids and previews returned for "Digital Marketing" search:
`[{
"unsplash_id": "ZSz1m4JPDqU",
"preview_url": "https://images.unsplash.com/photo-1530046614490-89e6f776b83b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "5VcSuWePr8Q",
"preview_url": "https://images.unsplash.com/photo-1522363757703-61225a8e04ab?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "mgYAR7BzBk4",
"preview_url": "https://images.unsplash.com/photo-1504203700686-f21e703e5f1c?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "zjCR_bfCHxA",
"preview_url": "https://images.unsplash.com/photo-1525211871029-4da752933b05?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "gWEnwzsYlEc",
"preview_url": "https://images.unsplash.com/photo-1495218368521-fc149bab5f9a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "LGHPAnaE-Ws",
"preview_url": "https://images.unsplash.com/photo-1525828404701-f213ceff9f6f?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "pRSken_15vQ",
"preview_url": "https://images.unsplash.com/photo-1526934188354-25fe58914ff2?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "L5IQUafkbWY",
"preview_url": "https://images.unsplash.com/photo-1520978159651-fcdf0b5c6651?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "Lw-WJ2t2Th0",
"preview_url": "https://images.unsplash.com/photo-1526934080044-d6b9f074b581?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
},
{
"unsplash_id": "Ts3yX7wDthw",
"preview_url": "https://images.unsplash.com/photo-1504205018232-cc789a59df70?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjc2Nzg1fQ"
}]`
