### ISSUE TITLE
Is Crew\Unsplash\Photo::create($file_path) still supported?

### ISSUE THREAD

**Issue by geskeitaloricardo** [unsplash/unsplash-php#105]
I'm trying to upload an image from my laravel app! But I get the following error:

> OAuth error: missing permissions 403

I have set 'write_photos'! So, probably I have the permissions!
I can use the others endpoints! This is the only one I can't!

**Comment by lukechesser** [comment]
Ah no, unfortunately that was removed from the API due to legal reasons out of our control. Sorry about that.

I'll remove the method and create a new release
