### ISSUE TITLE
Update guzzle to ^7.0

### ISSUE THREAD

**Issue by pmochine** [unsplash/unsplash-php#109]
Thanks :)

**Comment by SiroDiaz** [comment]
For upgrading to Laravel 8.x it is required to have installed guzzle ^7.0.1 so i recommend to open this issue again. Thanks.

**Comment by lukechesser** [comment]
@seojtix if someone wants to open a PR we'll merge it, but this isn't an actual issue, it's more of a feature requirement specific to one version of one framework

**Comment by pmochine** [comment]
@lukechesser Could you please bump up the release tag? It's still set to 2.4.2 
Thank you :)
