### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by freezy-sk** [unsplash/unsplash-php#12]
Hi
Are you planning to use some features introduced in PHP 5.5?
If not, what about lowering required version from `"php": ">=5.5.0"` to `"php": ">=5.4.0"` ?

**Comment by dechuck** [comment]
Hi @freezy-sk 

The main reason we use this version of PHP is because of `Guzzle 6.0`.
I'll see if we can support two version of Guzzle, depending of the PHP version.

I'll keep you updated.

**Comment by dechuck** [comment]
Since PHP 5.4 is deprecated, I will close this issue.
