### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by dechuck** [unsplash/unsplash-php#3]
The README is still missing some information about the different functionalities.

**Comment by lukechesser** [comment]
@dechuck what info is currently missing?

**Comment by dechuck** [comment]
I need to add the pagination part I completed this morning.
Also, I'll need someone to correct my grammar mistakes.

I'll wait for the guys feedback to know if we need to add more information or if everything make sense.

**Comment by lukechesser** [comment]
I'm going to go through grammar now ;)
