### ISSUE TITLE
How to get all photos using http method ?

### ISSUE THREAD

**Issue by designdodo** [unsplash/unsplash-php#35]
Hello

I need to get all photos from unplash photo stock through HTTP request ..like
I tried to get all photos using this ... { https://api.unsplash.com/photos/?client_id=My_application_ID }..

Can u provide me easy method to get all using HTTP action..

**Comment by dechuck** [comment]
Hey @designdodo,

This should help https://github.com/unsplash/unsplash-php#crewunsplashphotoallpage-per_page
It the wrapper method to fetch photos.

**Comment by dechuck** [comment]
If you have more questions, don’t hesitate to contact us at `api[at]unsplash[dot]com`
