### ISSUE TITLE
Having installation problem with composer because of guzzlehttp/guzzle version

### ISSUE THREAD

**Issue by taylankoca** [unsplash/unsplash-php#37]
Here is the output

Problem 1
    - Installation request for crewlabs/unsplash ^2.0 -> satisfiable by crewlabs/unsplash[2.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.2.0
    - Conclusion: don't install guzzlehttp/guzzle 6.2.0
    - crewlabs/unsplash 2.0.0 requires guzzlehttp/guzzle ~6.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 6.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 6.2.0) -> satisfiable by guzzlehttp/guzzle[6.2.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by dechuck** [comment]
Hey @taylankoca,
Which version of PHP are you using?

**Comment by taylankoca** [comment]
PHP 5.5.9-1

**Comment by dechuck** [comment]
I'll  try to replicate the issue around the end of the day. I'll let you know when I'll find the issue.

**Comment by dechuck** [comment]
Is it possible you install Guzzle 6.2.0 on an other project? Anyway, I'll update the guzzle dependency, it should fix your issue.

**Comment by taylankoca** [comment]
That would be great. Thank you very much.

**Comment by dechuck** [comment]
@taylankoca The last version of the package should fix your issue.
