### ISSUE TITLE
/search/photos response data

### ISSUE THREAD

**Issue by janhenckens** [unsplash/unsplash-php#44]
I'm adding a class for the new /search/response endpoint (here's what I have so far https://github.com/janhenckens/unsplash-php/commit/a594aefb5f4887109b9ec504407eaed383cec9b9) and the data I'm receiving back appears to be different from the other endpoint. 

By which I mean that passing it through the ArrayObject class gets me a different object structure then for example the /photo/curated endpoint.

Should I change something on my end? Thanks helping out!
Cheers

**Comment by janhenckens** [comment]
Hey crew! Has anyone had a chance to take a look at this? 
I'd like the finish the plugin I'm building and this is a blocking issue...

Thanks for getting back to me!
Jan

**Comment by aaronklaassen** [comment]
Hey @janhenckens - sorry about the wait, here. Yes, the search endpoints have a slightly different response format than the regular photo index ones. You can see an example in the documentation here: https://unsplash.com/documentation#search

If you have any more questions you can find me at api@unsplash.com.
