### ISSUE TITLE
Wrong rate limit values

### ISSUE THREAD

**Issue by taduuda** [unsplash/unsplash-php#47]
Hi, I'm getting some odd values when checking my rate limits in PHP.
![bildschirmfoto 2017-01-09 um 10 44 38](https://cloud.githubusercontent.com/assets/17167062/21762560/9fd725dc-d659-11e6-8aac-06d367a16170.PNG)

These are the functions I am using:
```
public function rateLimitTotal()
    {
        $limit = 50;
        if (!empty($this->headers[self::X_Ratelimit_Limit]) && is_array($this->headers[self::X_Ratelimit_Limit])) {
            $limit = (int) $this->headers[self::X_Ratelimit_Limit][0];
        }

        return $limit;
    }
```

```
    public function rateLimitRemaining()
    {
        $limit = 0;
        if (!empty($this->headers[self::X_Ratelimit_Remaining]) && is_array($this->headers[self::X_Ratelimit_Remaining])) {
            $limit = (int) $this->headers[self::X_Ratelimit_Remaining][0];
        }

        return $limit;
    }
```

Any idea on what's going wrong?

**Comment by aaronklaassen** [comment]
@tatuuda Yeah this is a known issue on the backend. You're not doing anything wrong. I'm going to close this issue because it's not a problem with `unsplash-php`, but don't worry we're working on it on our side. 😄
