### ISSUE TITLE
Everything is Private

### ISSUE THREAD

**Issue by The4Syndicate** [unsplash/unsplash-php#51]
After authenticating and running Unsplash\Photo::all(1, 30) it returns an ArrayObject in which everything is private. Can't access any of the properties.

**Comment by aaronklaassen** [comment]
@The4Syndicate Which private properties are you looking to access? There are public accessor functions available.

**Comment by The4Syndicate** [comment]
What are the functions for this?

private 'storage' (ArrayObject) is what I'm trying to access on any request of the Photo class.

**Comment by aaronklaassen** [comment]
Do you mean you're trying to access the `Photo` objects in the return value? It extends [ArrayObject](http://php.net/manual/en/class.arrayobject.php) - you can access its elements just like any other array:

```php
$photos = Crew\Unsplash\Photo::all();
$photos[0] // a Photo object
$photos[0]->urls["full"] // a URL string
```

I'm going to close this issue as this isn't the place for support. If you have any more questions though feel free to contact me at api@unsplash.com
