### ISSUE TITLE
Send UTM params

### ISSUE THREAD

**Issue by aaronklaassen** [unsplash/unsplash-php#58]
@lukechesser @HughbertD 

These days the API terms have this requirement: https://community.unsplash.com/developersblog/unsplash-api-terms-explained#block-yui_3_17_2_1_1490972762425_202608

But without being able to send arbitrary query params via the lib, clients can't do that. Since it should be attached to *every* request anyway, maybe the best way to do this is to make the `utm_source` value part of the lib config, and everything just gets attached automatically. i.e.,

```php
Crew\Unsplash\HttpClient::init([
	'applicationId'	=> 'YOUR APPLICATION ID',
        'secret'        => 'YOUR APPLICATION SECRET',
	'callbackUrl'	=> 'https://your-application.com/oauth/callback',
        'utmSource'     => 'my sweet app'
]);
```

or whatever.

For backwards compatibility, I'd log a warning if that value is missing from the config, but not fail outright.

**Comment by HughbertD** [comment]
@aaronklaassen If the user hasn't given their utmSource, do you want the links to either fall to a default and generate something like:
`?utm_source=nottracked&utm_medium=referral&utm_campaign=api-credit`

Or skip adding UTM parameters entirely? Wondering if _some_ data is better than none.

**Comment by aaronklaassen** [comment]
@HughbertD Good question. I'll get back to you.

**Comment by aaronklaassen** [comment]
@HughbertD Yeah put a placeholder value in - `api_app` works.

**Comment by lukechesser** [comment]
@aaronklaassen good thinking on this 👍
