### ISSUE TITLE
Update to `league/oauth2-client` ^2

### ISSUE THREAD

**Issue by brusch** [unsplash/unsplash-php#60]
Would be good to utilize the latest major branch of `league/oauth2-client` to avoid dependency issues with other packages.

**Comment by JamesHesterJr** [comment]
Is there any internal ambition to do this?

**Comment by lukechesser** [comment]
If you want to raise a PR, I think it would likely get merged. Sounds like there's support for it!

**Comment by paulm17** [comment]
I really need this, so I'm gonna fire off an email to support.

**Comment by JamesHesterJr** [comment]
Let me know if you need help with it. I could use it and might have the time to do it.

**Comment by paulm17** [comment]
I asked them if this was all that was needed...

https://github.com/unsplash/unsplash-php/blob/master/composer.json#L19

Changing "league/oauth2-client": "1.4.2", to "league/oauth2-client": ">=2.2.1", ?

**Comment by paulm17** [comment]
Seems like that's the first line is the only change.

I have 2.0 working, by hacking the process.  I installed with oauth2-client on it's own and then moved it to a directory elsewhere.

Then do the actual installation with all the packages I need with oauth2-client version 1.  After that, rename veraion 1 to oauth2-client-1.4.2 in the league directory under vendor.  Copy in version 2 from elsewhere earlier.

Now you have version 2.

**Comment by paulm17** [comment]
Oh and another reason for updating...  You need to, when upgrading to PHP 7.

https://github.com/thephpleague/oauth2-client/issues/650

**Comment by JamesHesterJr** [comment]
So I finally got around to looking into this. and as far as I can tell, it's actually just a tiny issue with the versioning. The league/oauth2-client package requires version ^1 which prevents v2 from working, but in fact it is capable of working with v2. I submitted a PR with explanation to get this fixed. The composer.lock used (and used with testing) actually uses V2 of the oauth2-client library. 

All he should have to do is change these characters, and potentially create a new composer.lock if he wants that shipped with the package.

Let me know if you need anything else.

https://github.com/HughbertD/oauth2-unsplash/pull/1

**Comment by aaronklaassen** [comment]
Hey folks sorry this took so long to get to - but you should be good to go with `v2.3.3`.

**Comment by paulm17** [comment]
Doesn't seem to work for me.

    Problem 1
	    - Installation request for crewlabs/unsplash 2.3.3 -> satisfiable by crewlabs/unsplash[2.3.3].
	    - crewlabs/unsplash 2.3.3 requires league/oauth2-client 1.4.2 -> satisfiable by league/oauth2-client[1.4.2] but these conflict with your requirements or minimum-stability.

Looking at the PR:  https://github.com/unsplash/unsplash-php/pull/67/commits/7b59e01bec447428cb1119f83589dc8271308fc8#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L19

I'm still seeing "league/oauth2-client": "1.4.2",

**Comment by aaronklaassen** [comment]
@paulm17 Ah dammit. Yeah I'll take another look.

**Comment by paulm17** [comment]
I posted above what I think the solution should be.  Happy to test when you update it again.
