### ISSUE TITLE
Photo::search using deprecated endpoint

### ISSUE THREAD

**Issue by 20k-ultra** [unsplash/unsplash-php#61]
I'm seeing a warning that says: 

`The photo search endpoint is deprecated. Use the new search endpoint instead. See: https://unsplash.com/documentation#search`

Still getting results though.

**Comment by lukechesser** [comment]
Ah yeah thats normal.

The old search API endpoint is deprecated and we encourage people to use `Search::photos()` instead. It looks like we need to update the README documentation though to list that and remove the documentation on the deprecated methods.

**Comment by lukechesser** [comment]
Closing in favour of #62 #63
