### ISSUE TITLE
New to composer install - having problems

### ISSUE THREAD

**Issue by dleigh** [unsplash/unsplash-php#66]
1st time doing a composer install.  Shared hosting environment.  I got the following message and cruising forums about composer installs and modifying composer.json didn't really help me - probably because I'm a newbie.  So with the following message what should I do next?
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package crewlabs/unsplash No version set (parsed as 1.0.0) is satisfiable by crewlabs/unsplash[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

```

**Comment by lukechesser** [comment]
Hey sorry @dleigh I'm not super sure either, but for questions, stackoverflow is your best bet. We have to reserve this for issues related to the code itself.
