### ISSUE TITLE
How to get photo API url  by  its download name?

### ISSUE THREAD

**Issue by danyj** [unsplash/unsplash-php#69]
Sorry if I am posting in a wrong git but cant seem to find a place to ask this. 
It is a great API but a huge thing has been missed by the devs. 
When you click on download image you get the image with a name that is mixed with user real name and some ID , 

for  example if you go here   https://unsplash.com/photos/pTgMXg2WrHY
and click on download 

you get  image by name ` nathan-anderson-268995.jpg`

now you dont have one reference in that image name that you could use with the API. 
No image ID , no actual username, nothing. 

We developed a WP theme with actual download names , now we are exporting  a demo and would like to bulk replace image names URL with a API url. No way we can do that now unless we go back , change all image names with image id from the URL.

**Comment by lukechesser** [comment]
Hey @danyj. Hmm, good point. We haven't come across anyone looking to do that before but it does make sense.

I'll add a feature request for the API team to look into supporting this.
