### ISSUE TITLE
2.4 requires packages of state dev-master

### ISSUE THREAD

**Issue by roelvanduijnhoven** [unsplash/unsplash-php#76]
The first problem is that I cannot update without changing the [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability).

The second problem is that every download of this repo will potentially result in a different version of that dev-master library. That is because libraries do not utilize a lock-file.

Error breakdown on my project:

```
$ composer update crewlabs/unsplash
Loading composer repositories with package information
Updating dependencies (including require-dev)                                  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crewlabs/unsplash ^2.4 -> satisfiable by crewlabs/unsplash[2.4.0].
    - crewlabs/unsplash 2.4.0 requires hughbertd/oauth2-unsplash dev-master -> satisfiable by hughbertd/oauth2-unsplash[dev-master] but these conflict with your requirements or minimum-stability.
```

I'll stick on 2.3 for now :). Thanks for the lib!

**Comment by lukechesser** [comment]
Thanks for letting us know @roelvanduijnhoven. I'm not super familiar with the PHP ecosystem, so will try to work through this.

@HughbertD can we update the stability of `oauth-2-unsplash`? Would that solve one of the problems here?

**Comment by roelvanduijnhoven** [comment]
@lukechesser @HughbertD If oauth2-unsplash cuts a new release, and we depend on that; that would solve both problems. 

The move to `dev-master` was made to facilitate https://github.com/unsplash/unsplash-php/issues/60 it seems.

**Comment by HughbertD** [comment]
@roelvanduijnhoven @lukechesser 

Could we just change the dependency in this repo's composer.json to:
`"hughbertd/oauth2-unsplash": ">=1.0.2"`

**Comment by lukechesser** [comment]
@HughbertD I have no idea haha. Whatever you guys think works

**Comment by roelvanduijnhoven** [comment]
Sorry @HughbertD only now saw your reaction on this issue.

That would work, but would mitigate the work done for #60 it seems. The newer commit https://github.com/HughbertD/oauth2-unsplash/commit/bfa14ffabd46c6fdb33eeeaff709a946e1399ea3 is necessary for that. And that commit is not on in the latest release.

So a new minor release of oauth2-unsplash to 1.0.3 would be all we need :).

Thanks.

**Comment by HughbertD** [comment]
The commit you mentioned is in the 1.0.2 version. (https://github.com/HughbertD/oauth2-unsplash/compare/1.0.2...master)

Would you like me to either:

- `composer update nothing` 
- `composer update` 

to generate a new lock file and release this as a new version? 

btw, feel free to make PRs against the repo if you have a suggested fix. :)

**Comment by roelvanduijnhoven** [comment]
> to generate a new lock file and release this as a new version?

Mm. I only now see that both these repos' use a lock file. A lock function has no purpose when somebody consumes it. So I would suggest removing it; this is wat most libraries do. Thus PR https://github.com/roelvanduijnhoven/oauth2-unsplash/pull/1 and https://github.com/roelvanduijnhoven/unsplash-php/pull/1.

> The commit you mentioned is in the 1.0.2 version.

You can browse the tree at 1.0.2. here: https://github.com/HughbertD/oauth2-unsplash/tree/1.0.2. And it does not include that commit. The link you show is the diff between master and that version ;). So I would suggest you release a new version 1.0.3 without doing any change. I cannot create a PR for this.

Thanks both!

**Comment by HughbertD** [comment]
Thanks, think I was getting the wrong end of the stick here.

**Comment by HughbertD** [comment]
Hi @roelvanduijnhoven 

I've updated oauth-unsplash with a new release (1.0.3) and packagist is showing the correct dependency requirements here: https://cl.ly/1C3M3t020B13

@lukechesser I think we can close this down now

**Comment by roelvanduijnhoven** [comment]
Thanks! I created a new PR that makes use of this :).

**Comment by lukechesser** [comment]
Thanks @HughbertD and @roelvanduijnhoven <3

**Comment by roelvanduijnhoven** [comment]
Thanks @lukechesser. Could you make a new release 2.4.1 with this in it?

After that I can update my app to trigger the Download end-point :).
