### ISSUE TITLE
Error message missing

### ISSUE THREAD

**Issue by ArmeniaH** [unsplash/unsplash-php#87]
Hey there

From time to time we are getting bad responses when doing

```\Crew\Unsplash\Search::photos('life', 1, 20);```

And we are getting status code out of this range

```return $response->getstatusCode() >= 200 && $response->getstatusCode() < 300;```

so we are getting an exception, but when we log it, we see the following

```Crew\Unsplash\Exception: [] in /app/vendor/crewlabs/unsplash/src/Endpoint.php:87```

Seems like the error message is missing and we don't know which part we are doing wrong, any idea why empty message ?

**Comment by ArmeniaH** [comment]
Tried to reproduce, and was able to get the status code, which is 503

**Comment by ArmeniaH** [comment]
Was also able to get the body of the guzzle response

<?xml version="1.0" encoding="utf-8"?>\n
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"\n
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\n
<html>\n
  <head>\n
    <title>503 first byte timeout</title>\n
  </head>\n
  <body>\n
    <h1>Error 503 first byte timeout</h1>\n
    <p>first byte timeout</p>\n
    <h3>Guru Mediation:</h3>\n
    <p>Details: cache-iad2120-IAD 1521635627 3170668008</p>\n
    <hr>\n
    <p>Varnish cache server</p>\n
  </body>\n
</html>

**Comment by ArmeniaH** [comment]
<img width="667" alt="screen shot 2018-03-21 at 4 37 02 pm" src="https://user-images.githubusercontent.com/4003433/37710146-36e17b70-2d26-11e8-85ef-c79a13a369cb.png">

Seems like the problem is with your services, this is impacting our live production, any news on this?

**Comment by aaronklaassen** [comment]
@ArmeniaH Yes, this was a problem with our API availability. You can track that via https://status.unsplash.com.

**Comment by ArmeniaH** [comment]
Still the code can be changed to detect this case and return corresponding error instead of empty message. Anyway, thanks for the response!
