### ISSUE TITLE
Photo类的parameters属性的权限为什么是private？这导致我调用Photo::all方法后无法取出数据

### ISSUE THREAD

**Issue by FrankDiao** [unsplash/unsplash-php#96]
Endpoint类中$parameters属性为什么是private？
我调用Photo::all方法后得到的数据都在parameters属性中，并且由于parameters属性的权限是private导致我无法取出数据。

**Comment by aaronklaassen** [comment]
You can access properties of a `Photo` object using the `->` operator.
